<a href="https://colab.research.google.com/github/radsrei/Caderno-Faculdade/blob/main/DS_Catolica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

05/08 - Aula NumPy
Utilizar Numpy para operações númericas eficientes, manipulação de arrays e fundamentos para Ciência de Dados

#Parte1: Introdução

In [ ]:
import numpy as np

###Listas

In [ ]:
#Array 1D com uma lista Python
lista = [1,2,3,4,5]
array_de_lista = np.array(lista)
print(array_de_lista)
print(array_de_lista.dtype)
array_de_lista

[1 2 3 4 5]
int64

array([1, 2, 3, 4, 5])

In [ ]:
#Array 2D com lista Python

lista_de_listas = [[1,2,3],[4,5,6],[7,8,9]]
array_de_listas = np.array(lista_de_listas)
print(array_de_listas)
array_de_listas

In [ ]:
# com zero
zero_ld = np.zeros(10)
print(zero_ld)
zero_ld

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# com uns
ones_ld = np.ones(10)
print(ones_ld)
ones_ld

In [ ]:
# com vazia
empty_ld = np.empty(10)
print(empty_ld)
empty_ld

In [ ]:
# shape é uma tupla
zeros_2d = np.zeros((3,3))
print(zeros_2d)
zeros_2d

In [ ]:
# com valor especifico
full_array = np.full((3,3), 7)
print(full_array)
full_array

###Sequências Numérias

In [ ]:
# np.arrange()

seq_1 = np.arange(10)
print(seq_1)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]

In [ ]:
#[start:stop:step]
seq_2 = np.arange(0, 20, 2)
print(seq_2)

In [ ]:
#[start:stop:num_elements]

linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

In [ ]:
#np.random.rand()
rand_array = np.random.rand(4)
print(rand_array)

[0.63151745 0.67351601 0.54582258 0.58715149]

In [ ]:
# np.random.randint(): [low:high:size]
randint_array = np.random.randint(0, 10, 5)
print(randint_array)

[6 0 1 5 1]

##Atributos importantes de um Array

In [ ]:
#dtype: tipo de dados dos elementos
array_de_lista.dtype

In [ ]:
#astype: mudar o tipo de dados dos elementos
rand_array_int = rand_array.astype(np.int64)
rand_array_int

array([0, 0, 0, 0])

In [ ]:
#shape: dimensões da tabela
randint_array.shape

(5,)

In [ ]:
#ndim: numero de dimensões array
rand_array.ndim

1

In [ ]:
#size: numero de elementos
rand_array.size

In [ ]:
# nbytes: tamanho total do array em bytes
rand_array.nybets

NameError: name 'rand_array' is not defined

#Parte 2: Operações com Array

##Operações Aritméticas

In [ ]:
arr_op1 = np.array([1,2,3])
arr_op2 = np.array([4,5,6])

#soma de arrays
arr_op1 + arr_op2

array([5, 7, 9])

In [ ]:
#multipliacação de array
arr_op1 * arr_op2

array([ 4, 10, 18])

In [ ]:
# Operações escalares
print(arr_op2 + 10)
print(arr_op2 * 10)
print(arr_op1 / 2)

[14 15 16]
[40 50 60]
[0.5 1.  1.5]

##Indexação

In [ ]:
# acessando um elemento (1D)
arr_1d = np.array(0,20)
print(arr_1d)

print('Primeiro Elemento índice 0:', arr_1d[0])
print('Décimo Eleme to índice 9:',arr_1d[9])
print('Ultimo Elemento índice -1:', arr_1d[-1])

In [ ]:
# acessando um elemento (2D)
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matriz: \n', matriz)

Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
# linha, coluna
print(matriz[0,1])
print(matriz[2,2])

##Slicing

In [ ]:
# [start:stop:step] - Stop é exclusivo

print('Elementos do índice 2 ao 5:',arr_1d[2:6])
print('Elementos do inicio até o índice 5', arr_1d[:6])
print('Elementos do índice 2 até o final', arr_1d[2:])
print('Elementos com passo de 2:', arr_1d[::2])
print('Elementos em ordem reversa:', arr_1d[::-1])

In [ ]:
#Slicing e atribuição
arr_1d_mod = np.copy(arr_1d)
arr_1d_mod[0:3] = 99
print(arr_1d_mod)

NameError: name 'arr_1d' is not defined

In [ ]:
#slicing/atribuição nd
#[Star_row:stop_row, start_col:stop_col]
matriz[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#todas as linhas, coluna específica
matriz[:,2]

array([3, 6, 9])

In [ ]:
#linha especifica, todas as colunas
matriz[1,:]

array([4, 5, 6])

In [ ]:
#selecionar linhas especificar e todas as colunas
matriz[[0,2],:]

# Parte 3: Biblioteca Panda
## Pandas é uma ferramenta essencial para a manipulação de dados em Python. Vamos explorar 2 estruturas de dados em pandas:
**Series**
**DataFrames**

## Etapa 1: Com dados digitados

In [ ]:
import pandas as pd

### Criando Series

Uma Serie é um array unidimensonal com rótulos (índices)

In [ ]:
# Criar uma Serie a partir de uma lista

s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Acessando os valores e índices

In [ ]:
# acessando os valores da series
print(s.values)

[10 20 30 40 50]

In [ ]:
# acessando os indices da series
print(s.index)

RangeIndex(start=0, stop=5, step=1)

### Criando uma Serie com índices Personalizados

In [ ]:
s2 = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
print(s2)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
s2[s2>4]

a    10
b    20
c    30
d    40
e    50
dtype: int64

### DataFrame

Uma estrutura de dados tabular bidimensional com eixos rotulados

In [ ]:
# Criando um DataFrame a partir de um dicionário
dados = {'Nome': ['Alice', 'Bob', 'Charlie', 'David'],
         'Idade': [25, 30, 35, 40],
         'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre']}

In [ ]:
df_br = pd.DataFrame(dados)
print(df_br)

      Nome  Idade          Cidade
0    Alice     25       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     35  Belo Horizonte
3    David     40    Porto Alegre

###Acessar e manipular dados no DataFrame

In [ ]:
# visualização das linhas iniciais
print(df_br.head(3))

      Nome  Idade          Cidade
0    Alice     25       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     35  Belo Horizonte

In [ ]:
# visualizar linhas finais
print(df_br.tail(2))

      Nome  Idade          Cidade
2  Charlie     35  Belo Horizonte
3    David     40    Porto Alegre

In [ ]:
# visualizar linha aleatória
print(df_br.sample(2))

      Nome  Idade          Cidade
2  Charlie     35  Belo Horizonte
0    Alice     25       São Paulo

### Acessando Colunas ou mudando colunas de posição

In [ ]:
# Acessar a coluna 'Cidade'
print(df_br['Cidade'])

0         São Paulo
1    Rio de Janeiro
2    Belo Horizonte
3      Porto Alegre
Name: Cidade, dtype: object

In [ ]:
# Mudar colunas de posição
df2_br = pd.DataFrame(dados, columns=['Cidade', 'Nome', 'Idade'])
print(df2_br)

           Cidade     Nome  Idade
0       São Paulo    Alice     25
1  Rio de Janeiro      Bob     30
2  Belo Horizonte  Charlie     35
3    Porto Alegre    David     40

###Adicionar uma nova Coluna

In [ ]:
df2_br['Altura'] = [1.65, 1.70, 1.75, 1.80]
print(df2_br)

###Adicionar uma coluna do tipo Booleano

In [ ]:
# Coluna boolean
df2_br['>10']=df2_br['Idade']>10
print(df2_br)

###Exclusão ou modificação de dados (linhas, colunas)

In [ ]:
# Excluir
df2_br.drop('Altura', axis=1, inplace=True)
print(df2_br)

##Etapa 2:Carregando Dados de Fontes Externas

In [2]:
import seaborn as sns

Neste tutorial, será carregado um dataser classíco, o do titanic, usando a biblioteca Seaborn.

In [3]:
# Carregar o dataset
df = sns.load_dataset('titanic')

### Exploração e Inspeção de Dados

In [4]:
# Visualizar as primeiras linhas
display(df.head(10))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [ ]:
# Visualizar as ultimas linhas
display(df.tail(10))

In [ ]:
# Visualizar amostra
display(df.sample(5))

In [ ]:
# obter informações sobre a estrutura
df.info()

In [ ]:
# Tabela estátistica
df.describe()

### Seleção e Filtragem de dados

Seleção de Colunas

In [5]:
df['age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [6]:
df[['age','sex','alive']].head()

    age     sex alive
0  22.0    male    no
1  38.0  female   yes
2  26.0  female   yes
3  35.0  female   yes
4  35.0    male    no

###Selecionando Linhas e colunas com Loc e Iloc

.loc: acessa por rótulos dos índices e das colunas

.iloc: acessa por posição int

In [7]:
df.loc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [8]:
# Selecionar a primeira linha posição 0
df.iloc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [9]:
# Selecionar as linhas de 0 a 4 e apenas colunas age e sex
df.loc[0:4,['sex','age']]

      sex   age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0

In [ ]:
# Seleciona 5 linhas e 3 colunas
df.iloc[0:5,0:3]

In [10]:
# Filtar apenas passageiros da primeira classe
df[df['class']=='First']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [11]:
#filtrar passageiros com mais de 50 anos
df[df['age']>50]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,1,1,female,52.0,1,1,93.5000,S,First,woman,False,B,Southampton,yes,False
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [13]:
# Combinar multiplas condições
df[(df['age']>50) & (df['sex']=='male') & (df['class'] == 'First')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
124,0,1,male,54.0,0,1,77.2875,S,First,man,True,D,Southampton,no,False
155,0,1,male,51.0,0,1,61.3792,C,First,man,True,NaN,Cherbourg,no,False
170,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
174,0,1,male,56.0,0,0,30.6958,C,First,man,True,A,Cherbourg,no,True
252,0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True
262,0,1,male,52.0,1,1,79.6500,S,First,man,True,E,Southampton,no,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
449,1,1,male,52.0,0,0,30.5000,S,First,man,True,C,Southampton,yes,True
456,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
467,0,1,male,56.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
487,0,1,male,58.0,0,0,29.7000,C,First,man,True,B,Cherbourg,no,True
492,0,1,male,55.0,0,0,30.5000,S,First,man,True,C,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
545,0,1,male,64.0,0,0,26.0000,S,First,man,True,NaN,Southampton,no,True
555,0,1,male,62.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
587,1,1,male,60.0,1,1,79.2000,C,First,man,True,B,Cherbourg,yes,False
625,0,1,male,61.0,0,0,32.3208,S,First,man,True,D,Southampton,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
647,1,1,male,56.0,0,0,35.5000,C,First,man,True,A,Cherbourg,yes,True
659,0,1,male,58.0,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
694,0,1,male,60.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True

###Lidando com dados Nulos

In [ ]:
# Verificar a quantidade de registros nulos
df.isnull().sum()

In [ ]:
# preencher os valores ausentes
media_idade = df['age'].mean()
df_preenchido = df.copy()
df_preenchido['age'].fillna(media_idade, inplace=True)

df_preenchido['age'].isnull().sum()

In [14]:
# remover linhas (registros) com células nulas
df_removido = df.dropna(subset=['age'])
df_removido.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           530
embark_town      2
alive            0
alone            0
dtype: int64

###Agrupamento

In [15]:
#agrupar por 'sex' e calcular taxa de sobrevivencia
media_sobrevivente_sexo = df.groupby('sex')['survived'].mean()
print(media_sobrevivente_sexo)

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [16]:
# agrupar por class e sex
media_sobrevivente_class_sex = df.groupby(['class','sex'])['survived'].mean()
print(media_sobrevivente_class_sex)

class   sex
First   female    0.968085
        male      0.368852
Second  female    0.921053
        male      0.157407
Third   female    0.500000
        male      0.135447
Name: survived, dtype: float64

/tmp/ipython-input-3254363991.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  media_sobrevivente_class_sex = df.groupby(['class','sex'])['survived'].mean()